// <auto-generated />
using System;
using CalorieTracker.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalorieTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260909182900_AddUserIdToFoodItemOnly")]
    partial class AddUserIdToFoodItemOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("CalorieTracker.Shared.FoodItemDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Calories")
                        .HasColumnType("REAL");

                    b.Property<double>("CarbsGrams")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ConsumedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("FatGrams")
                        .HasColumnType("REAL");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MealType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalQuery")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Portion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ProteinGrams")
                        .HasColumnType("REAL");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ConsumedDate");

                    b.ToTable("FoodItems");
                });
#pragma warning restore 612, 618
        }
    }
}
